### ISSUE TITLE
An example fastmri.yaml to run

### ISSUE THREAD

**Issue by Graeme-Lee** [neuraloperator/mri#1]
When I try to reproduce this work, I met the problem and found no example yaml file

**Comment by Jonvi-Lau** [comment]
I encountered the same issue. When I ran ./scripts/knee_multipatt.sh, I got a FileNotFoundError: No such file or directory: 'fastmri.yaml'

**Comment by armeetj** [comment]
Here's an example `fastmri.yaml` file, as detailed in the README.
I'll add a mechanism in the code that generates the default config if not found soon. Apologies for the late response.

```
log_path: /tmp/logs
checkpoint_path: /tmp/checkpoints

lmdb:
  knee_train_path: **/**/**/knee_train_lmdb
  knee_val_path: **/**/**/knee_val_lmdb
  brain_train_path: **/**/**/brain_train_lmdb
  brain_val_path: **/**/**/brain_val_lmdb
```
